import { ProductType } from '@/types';

export const MOCK_PRODUCTS: ProductType[] = [
  {
    id: '1',
    name: 'Kashmir Saffron',
    slug: 'kashmir-saffron',
    description:
      'Hand-picked from the pristine fields of Pampore, Kashmir — the saffron capital of India. Each thread is carefully selected to ensure the highest grade (Mongra) quality. Our saffron delivers an intense golden hue, a floral-honey aroma, and an unmistakable flavor that transforms biryanis, desserts, and teas into culinary masterpieces.',
    shortDescription: 'Premium Grade-1 Mongra saffron from Pampore, Kashmir',
    price: 899,
    compareAtPrice: 1199,
    image: '/images/products/saffron.png',
    images: ['/images/products/saffron.png', '/images/products/saffron.png', '/images/products/saffron.png'],
    category: 'premium',
    tags: ['premium', 'kashmiri', 'organic'],
    variants: [
      { weight: '1g', price: 899, sku: 'SAF-1G' },
      { weight: '2g', price: 1699, sku: 'SAF-2G' },
      { weight: '5g', price: 3999, sku: 'SAF-5G' },
    ],
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Pampore, Kashmir',
  },
  {
    id: '2',
    name: 'Organic Turmeric Powder',
    slug: 'organic-turmeric-powder',
    description:
      'Sourced from the lush Lakadong region of Meghalaya, known for producing turmeric with the highest curcumin content in the world (7-12%). This vibrant golden powder is sun-dried and stone-ground to preserve its potent anti-inflammatory properties and deep earthy flavour.',
    shortDescription: 'High-curcumin Lakadong turmeric from Meghalaya',
    price: 249,
    compareAtPrice: 349,
    image: '/images/products/turmeric.png',
    featuredImage: '/images/products/featured/turmeric1.png',
    images: ['/images/products/turmeric.png', '/images/products/turmeric.png', '/images/products/turmeric.png'],
    category: 'ground-spices',
    tags: ['organic', 'superfood', 'bestseller'],
    variants: [
      { weight: '100g', price: 249, sku: 'TUR-100G' },
      { weight: '250g', price: 549, sku: 'TUR-250G' },
      { weight: '500g', price: 999, sku: 'TUR-500G' },
    ],
    rating: 4.8,
    reviewCount: 512,
    inStock: true,
    isFeatured: true,
    isNew: false,
    origin: 'Lakadong, Meghalaya',
  },
  {
    id: '3',
    name: 'Green Cardamom Pods',
    slug: 'green-cardamom-pods',
    description:
      'Aromatic green cardamom pods from the misty hills of Kerala\'s Idukki district. These bold, plump pods burst with a complex symphony of eucalyptus, mint, and citrus notes. Perfect for chai, biryanis, and Indian desserts like kheer and gulab jamun.',
    shortDescription: 'Bold 8mm+ green cardamom from Kerala highlands',
    price: 399,
    image: '/images/products/cardamom.png',
    featuredImage: '/images/products/featured/cardamom1.png',
    images: ['/images/products/cardamom.png', '/images/products/cardamom.png', '/images/products/cardamom.png'],
    category: 'whole-spices',
    tags: ['aromatic', 'premium', 'kerala'],
    variants: [
      { weight: '50g', price: 399, sku: 'CAR-50G' },
      { weight: '100g', price: 749, sku: 'CAR-100G' },
      { weight: '250g', price: 1699, sku: 'CAR-250G' },
    ],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    isFeatured: true,
    isNew: true,
    origin: 'Idukki, Kerala',
  },
  {
    id: '4',
    name: 'Ceylon Cinnamon Sticks',
    slug: 'ceylon-cinnamon-sticks',
    description:
      'True Ceylon cinnamon (Cinnamomum verum) — delicate, multi-layered quills with a sweet, refined flavour far superior to common cassia. Each stick is hand-rolled from the inner bark of young cinnamon trees. Ideal for slow-cooked curries, warm beverages, and festive desserts.',
    shortDescription: 'Hand-rolled true Ceylon cinnamon quills',
    price: 349,
    image: '/images/products/cinnamon.png',
    images: ['/images/products/cinnamon.png', '/images/products/cinnamon.png', '/images/products/cinnamon.png'],
    category: 'whole-spices',
    tags: ['ceylon', 'aromatic', 'baking'],
    variants: [
      { weight: '50g', price: 349, sku: 'CIN-50G' },
      { weight: '100g', price: 649, sku: 'CIN-100G' },
      { weight: '200g', price: 1199, sku: 'CIN-200G' },
    ],
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Sri Lanka',
  },
  {
    id: '5',
    name: 'Whole Cumin Seeds',
    slug: 'whole-cumin-seeds',
    description:
      'Premium cumin seeds from the arid fields of Rajasthan, sun-dried to lock in their warm, earthy, slightly peppery aroma. These seeds are the backbone of Indian tempering (tadka) and an essential ingredient in spice blends worldwide. Roast them lightly to unlock their full, nutty depth.',
    shortDescription: 'Sun-dried Rajasthani cumin with intense aroma',
    price: 149,
    image: '/images/products/cumin.png',
    images: ['/images/products/cumin.png', '/images/products/cumin.png', '/images/products/cumin.png'],
    category: 'whole-spices',
    tags: ['essential', 'rajasthani', 'tadka'],
    variants: [
      { weight: '100g', price: 149, sku: 'CUM-100G' },
      { weight: '250g', price: 329, sku: 'CUM-250G' },
      { weight: '500g', price: 599, sku: 'CUM-500G' },
    ],
    rating: 4.5,
    reviewCount: 378,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Jodhpur, Rajasthan',
  },
  {
    id: '6',
    name: 'Kashmiri Red Chili Powder',
    slug: 'kashmiri-red-chili-powder',
    description:
      'Vibrant crimson Kashmiri chili powder, prized for its stunning color and mild, fruity heat. Unlike harsh chili powders, this variety adds rich colour to gravies, tandoori marinades, and curries without overwhelming spiciness — a secret weapon in every Indian kitchen.',
    shortDescription: 'Mild, vibrant red chili for colour and flavour',
    price: 199,
    image: '/images/products/chili.png',
    featuredImage: '/images/products/featured/chilli.png',
    images: ['/images/products/chili.png', '/images/products/chili.png', '/images/products/chili.png'],
    category: 'ground-spices',
    tags: ['kashmiri', 'mild', 'colourful'],
    variants: [
      { weight: '100g', price: 199, sku: 'CHI-100G' },
      { weight: '250g', price: 449, sku: 'CHI-250G' },
      { weight: '500g', price: 849, sku: 'CHI-500G' },
    ],
    rating: 4.7,
    reviewCount: 267,
    inStock: true,
    isFeatured: true,
    isNew: false,
    origin: 'Srinagar, Kashmir',
  },
  {
    id: '7',
    name: "Leela's Garam Masala",
    slug: 'leelas-garam-masala',
    description:
      "Our signature house blend — a carefully balanced symphony of 12 whole spices, including cardamom, cloves, cinnamon, black pepper, and bay leaves. Each batch is small-quantity roasted and stone-ground to order, ensuring peak freshness and complexity. This is the finishing spice that defines Leela's kitchen philosophy.",
    shortDescription: 'Signature 12-spice house blend, ground to order',
    price: 299,
    image: '/images/products/garam-masala.png',
    images: ['/images/products/garam-masala.png', '/images/products/garam-masala.png', '/images/products/garam-masala.png'],
    category: 'spice-blends',
    tags: ['signature', 'blend', 'bestseller'],
    variants: [
      { weight: '100g', price: 299, sku: 'GAR-100G' },
      { weight: '250g', price: 699, sku: 'GAR-250G' },
      { weight: '500g', price: 1299, sku: 'GAR-500G' },
    ],
    rating: 4.9,
    reviewCount: 623,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Leela\'s Kitchen, India',
  },
  {
    id: '8',
    name: 'Star Anise',
    slug: 'star-anise',
    description:
      'Beautiful, whole star-shaped pods from the evergreen forests of Northeast India. Each pod is packed with a warm, sweet, liquorice-like flavour that enhances biryanis, slow-cooked stews, and chai. A little goes a long way — 2-3 stars can perfume an entire dish.',
    shortDescription: 'Whole star-shaped pods with sweet anise flavour',
    price: 199,
    image: '/images/products/star-anise.png',
    images: ['/images/products/star-anise.png', '/images/products/star-anise.png', '/images/products/star-anise.png'],
    category: 'whole-spices',
    tags: ['aromatic', 'biryani', 'chai'],
    variants: [
      { weight: '50g', price: 199, sku: 'STA-50G' },
      { weight: '100g', price: 369, sku: 'STA-100G' },
      { weight: '200g', price: 699, sku: 'STA-200G' },
    ],
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    isFeatured: false,
    isNew: true,
    origin: 'Arunachal Pradesh',
  },
  {
    id: '9',
    name: 'Black Peppercorns',
    slug: 'black-peppercorns',
    description: 'Premium Black Peppercorns sourced directly from Wayanad, Kerala. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Black Peppercorns from Wayanad, Kerala',
    price: 199,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 199, sku: 'BLA-100G' },
      { weight: '250g', price: 437, sku: 'BLA-250G' },
    ],
    rating: 4.9,
    reviewCount: 113,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Wayanad, Kerala',
  },
  {
    id: '10',
    name: 'Whole Cloves',
    slug: 'whole-cloves',
    description: 'Premium Whole Cloves sourced directly from Tamil Nadu. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Whole Cloves from Tamil Nadu',
    price: 249,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 249, sku: 'WHO-100G' },
      { weight: '250g', price: 547, sku: 'WHO-250G' },
    ],
    rating: 4.5,
    reviewCount: 120,
    inStock: true,
    isFeatured: false,
    isNew: true,
    origin: 'Tamil Nadu',
  },
  {
    id: '11',
    name: 'Coriander Seeds',
    slug: 'coriander-seeds',
    description: 'Premium Coriander Seeds sourced directly from Gujarat. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Coriander Seeds from Gujarat',
    price: 129,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 129, sku: 'COR-100G' },
      { weight: '250g', price: 283, sku: 'COR-250G' },
    ],
    rating: 4.6,
    reviewCount: 127,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Gujarat',
  },
  {
    id: '12',
    name: 'Fennel Seeds',
    slug: 'fennel-seeds',
    description: 'Premium Fennel Seeds sourced directly from Rajasthan. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Fennel Seeds from Rajasthan',
    price: 139,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 139, sku: 'FEN-100G' },
      { weight: '250g', price: 305, sku: 'FEN-250G' },
    ],
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Rajasthan',
  },
  {
    id: '13',
    name: 'Black Mustard Seeds',
    slug: 'black-mustard-seeds',
    description: 'Premium Black Mustard Seeds sourced directly from Madhya Pradesh. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Black Mustard Seeds from Madhya Pradesh',
    price: 89,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 89, sku: 'BLA-100G' },
      { weight: '250g', price: 195, sku: 'BLA-250G' },
    ],
    rating: 4.8,
    reviewCount: 141,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Madhya Pradesh',
  },
  {
    id: '14',
    name: 'Fenugreek Seeds',
    slug: 'fenugreek-seeds',
    description: 'Premium Fenugreek Seeds sourced directly from Rajasthan. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Fenugreek Seeds from Rajasthan',
    price: 99,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 99, sku: 'FEN-100G' },
      { weight: '250g', price: 217, sku: 'FEN-250G' },
    ],
    rating: 4.9,
    reviewCount: 148,
    inStock: true,
    isFeatured: true,
    isNew: false,
    origin: 'Rajasthan',
  },
  {
    id: '15',
    name: 'Premium Mace (Javitri)',
    slug: 'premium-mace-javitri',
    description: 'Premium Premium Mace (Javitri) sourced directly from Kerala. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Premium Mace (Javitri) from Kerala',
    price: 499,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'premium',
    tags: ['premium', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 499, sku: 'PRE-100G' },
      { weight: '250g', price: 1097, sku: 'PRE-250G' },
    ],
    rating: 4.5,
    reviewCount: 155,
    inStock: true,
    isFeatured: false,
    isNew: true,
    origin: 'Kerala',
  },
  {
    id: '16',
    name: 'Whole Nutmeg',
    slug: 'whole-nutmeg',
    description: 'Premium Whole Nutmeg sourced directly from Kerala. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Whole Nutmeg from Kerala',
    price: 299,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 299, sku: 'WHO-100G' },
      { weight: '250g', price: 657, sku: 'WHO-250G' },
    ],
    rating: 4.6,
    reviewCount: 162,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Kerala',
  },
  {
    id: '17',
    name: 'Coriander Powder',
    slug: 'coriander-powder',
    description: 'Premium Coriander Powder sourced directly from Gujarat. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Coriander Powder from Gujarat',
    price: 149,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'ground-spices',
    tags: ['ground', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 149, sku: 'COR-100G' },
      { weight: '250g', price: 327, sku: 'COR-250G' },
    ],
    rating: 4.7,
    reviewCount: 169,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Gujarat',
  },
  {
    id: '18',
    name: 'Roasted Cumin Powder',
    slug: 'roasted-cumin-powder',
    description: 'Premium Roasted Cumin Powder sourced directly from Rajasthan. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Roasted Cumin Powder from Rajasthan',
    price: 179,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'ground-spices',
    tags: ['ground', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 179, sku: 'ROA-100G' },
      { weight: '250g', price: 393, sku: 'ROA-250G' },
    ],
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Rajasthan',
  },
  {
    id: '19',
    name: 'Black Salt (Kala Namak)',
    slug: 'black-salt-kala-namak',
    description: 'Premium Black Salt (Kala Namak) sourced directly from Himalayas. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Black Salt (Kala Namak) from Himalayas',
    price: 79,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'essentials',
    tags: ['essentials', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 79, sku: 'BLA-100G' },
      { weight: '250g', price: 173, sku: 'BLA-250G' },
    ],
    rating: 4.9,
    reviewCount: 183,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Himalayas',
  },
  {
    id: '20',
    name: 'Amchur (Dry Mango) Powder',
    slug: 'amchur-dry-mango-powder',
    description: 'Premium Amchur (Dry Mango) Powder sourced directly from Uttar Pradesh. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Amchur (Dry Mango) Powder from Uttar Pradesh',
    price: 189,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'ground-spices',
    tags: ['ground', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 189, sku: 'AMC-100G' },
      { weight: '250g', price: 415, sku: 'AMC-250G' },
    ],
    rating: 4.5,
    reviewCount: 190,
    inStock: true,
    isFeatured: false,
    isNew: true,
    origin: 'Uttar Pradesh',
  },
  {
    id: '21',
    name: 'Asafoetida (Premium Hing)',
    slug: 'asafoetida-premium-hing',
    description: 'Premium Asafoetida (Premium Hing) sourced directly from Afghanistan/India. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Asafoetida (Premium Hing) from Afghanistan/India',
    price: 349,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'essentials',
    tags: ['essentials', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 349, sku: 'ASA-100G' },
      { weight: '250g', price: 767, sku: 'ASA-250G' },
    ],
    rating: 4.6,
    reviewCount: 197,
    inStock: true,
    isFeatured: true,
    isNew: false,
    origin: 'Afghanistan/India',
  },
  {
    id: '22',
    name: 'Hyderabadi Biryani Masala',
    slug: 'hyderabadi-biryani-masala',
    description: 'Premium Hyderabadi Biryani Masala sourced directly from Hyderabad. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Hyderabadi Biryani Masala from Hyderabad',
    price: 249,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'spice-blends',
    tags: ['spice', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 249, sku: 'HYD-100G' },
      { weight: '250g', price: 547, sku: 'HYD-250G' },
    ],
    rating: 4.7,
    reviewCount: 204,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Hyderabad',
  },
  {
    id: '23',
    name: 'Authentic Chai Masala',
    slug: 'authentic-chai-masala',
    description: 'Premium Authentic Chai Masala sourced directly from Kerala. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Authentic Chai Masala from Kerala',
    price: 199,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'spice-blends',
    tags: ['spice', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 199, sku: 'AUT-100G' },
      { weight: '250g', price: 437, sku: 'AUT-250G' },
    ],
    rating: 4.8,
    reviewCount: 211,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Kerala',
  },
  {
    id: '24',
    name: 'Traditional Sambar Powder',
    slug: 'traditional-sambar-powder',
    description: 'Premium Traditional Sambar Powder sourced directly from Tamil Nadu. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Traditional Sambar Powder from Tamil Nadu',
    price: 179,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'spice-blends',
    tags: ['spice', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 179, sku: 'TRA-100G' },
      { weight: '250g', price: 393, sku: 'TRA-250G' },
    ],
    rating: 4.9,
    reviewCount: 218,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Tamil Nadu',
  },
  {
    id: '25',
    name: 'Malabar Rasam Powder',
    slug: 'malabar-rasam-powder',
    description: 'Premium Malabar Rasam Powder sourced directly from Kerala. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Malabar Rasam Powder from Kerala',
    price: 169,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'spice-blends',
    tags: ['spice', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 169, sku: 'MAL-100G' },
      { weight: '250g', price: 371, sku: 'MAL-250G' },
    ],
    rating: 4.5,
    reviewCount: 225,
    inStock: true,
    isFeatured: false,
    isNew: true,
    origin: 'Kerala',
  },
  {
    id: '26',
    name: 'Smoky Tandoori Masala',
    slug: 'smoky-tandoori-masala',
    description: 'Premium Smoky Tandoori Masala sourced directly from Punjab. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Smoky Tandoori Masala from Punjab',
    price: 229,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'spice-blends',
    tags: ['spice', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 229, sku: 'SMO-100G' },
      { weight: '250g', price: 503, sku: 'SMO-250G' },
    ],
    rating: 4.6,
    reviewCount: 232,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Punjab',
  },
  {
    id: '27',
    name: 'Guntur Red Chili (Whole)',
    slug: 'guntur-red-chili-whole',
    description: 'Premium Guntur Red Chili (Whole) sourced directly from Andhra Pradesh. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Guntur Red Chili (Whole) from Andhra Pradesh',
    price: 159,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 159, sku: 'GUN-100G' },
      { weight: '250g', price: 349, sku: 'GUN-250G' },
    ],
    rating: 4.7,
    reviewCount: 239,
    inStock: true,
    isFeatured: false,
    isNew: false,
    origin: 'Andhra Pradesh',
  },
  {
    id: '28',
    name: 'Byadgi Chili (Whole)',
    slug: 'byadgi-chili-whole',
    description: 'Premium Byadgi Chili (Whole) sourced directly from Karnataka. Carefully selected and processed to maintain the highest quality and authentic flavor profile.',
    shortDescription: 'Premium quality Byadgi Chili (Whole) from Karnataka',
    price: 219,
    image: '/images/products/placeholder.png',
    images: ['/images/products/placeholder.png'],
    category: 'whole-spices',
    tags: ['whole', 'authentic', 'premium'],
    variants: [
      { weight: '100g', price: 219, sku: 'BYA-100G' },
      { weight: '250g', price: 481, sku: 'BYA-250G' },
    ],
    rating: 4.8,
    reviewCount: 246,
    inStock: true,
    isFeatured: true,
    isNew: false,
    origin: 'Karnataka',
  },
];
