import { RecipeType } from '@/types';

export const RECOMMENDED_RECIPES: RecipeType[] = [
  {
    id: 'r1',
    title: 'Smoothie Bowl',
    slug: 'smoothie-bowl',
    description: 'Learn how to make the best smoothie bowl recipe with 5 ingredients in 5 minutes!',
    image: '/images/recipes/smoothie-bowl.png',
    category: 'Bowl',
    calories: '220kcal',
    time: '5min',
    difficulty: 'Easy',
    likes: '21.8K',
    views: '156.1K',
    isNew: true,
  },
  {
    id: 'r2',
    title: 'Seared Scallops with White Beans',
    slug: 'seared-scallops',
    description: 'This recipe for seared scallops with white beans and spinach turns out a healthy dinner.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=2070&auto=format&fit=crop',
    category: 'Main dish',
    calories: '420kcal',
    time: '20min',
    difficulty: 'Hard',
    likes: '7.1K',
    views: '156.1K',
    isNew: true,
  },
  {
    id: 'r3',
    title: 'The Only High-Protein Veggie Sandwich',
    slug: 'veggie-sandwich',
    description: 'From beans to tofu to tempeh bacon, this high-protein veggie sandwich formula can...',
    image: '/images/recipes/veggie-sandwich.png',
    category: 'Sandwich',
    calories: '250kcal',
    time: '15min',
    difficulty: 'Easy',
    likes: '1.1K',
    views: '156.1K',
  },
];

export const POPULAR_RECIPES: RecipeType[] = [
  {
    id: 'p1',
    title: 'Mushroom Quiche',
    slug: 'mushroom-quiche',
    description: 'A crustless salmon and spinach quiche that\'s healthy and easy to make.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=1974&auto=format&fit=crop',
    category: 'Breakfast',
    calories: '310kcal',
    time: '45min',
    difficulty: 'Medium',
    likes: '12K',
    views: '98K',
  },
  {
    id: 'p2',
    title: 'Spinach Breakfast Taco',
    slug: 'spinach-taco',
    description: 'It doesn\'t get easier than this healthy breakfast taco that\'s ready in minutes.',
    image: '/images/recipes/spinach-taco.png',
    category: 'Breakfast',
    calories: '180kcal',
    time: '10min',
    difficulty: 'Easy',
    likes: '5.4K',
    views: '42K',
  },
  {
    id: 'p3',
    title: 'Strawberry Spinach Salad',
    slug: 'strawberry-salad',
    description: 'Serve this summery strawberry spinach salad alongside soup or...',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2070&auto=format&fit=crop',
    category: 'Salad',
    calories: '150kcal',
    time: '15min',
    difficulty: 'Easy',
    likes: '3.2K',
    views: '28K',
  },
  {
    id: 'p4',
    title: 'Cottage Cheese Toast',
    slug: 'cottage-cheese-toast',
    description: 'This toast, made with whole-grain bread and topped with creamy...',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=2080&auto=format&fit=crop',
    category: 'Snack',
    calories: '210kcal',
    time: '5min',
    difficulty: 'Easy',
    likes: '8.9K',
    views: '65K',
  },
];
